### ISSUE TITLE
Follow Tags переводы не работают

### ISSUE THREAD

**Issue by akairat** [marketplace-flarum/flarum-l10n-ext-russian#5]
**Flarum version 0.1.0-beta.15**

**Composer.json**
<img width="579" alt="Screen Shot 2021-03-15 at 5 49 21 PM" src="https://user-images.githubusercontent.com/9755669/111239674-e6f09280-85b6-11eb-9efb-eda8f76492f7.png">

**Станица тэга**
<img width="322" alt="Screen Shot 2021-03-15 at 5 51 03 PM" src="https://user-images.githubusercontent.com/9755669/111239755-17d0c780-85b7-11eb-9d01-863061d17886.png">

**Linguist переводов тоже не видит**
<img width="439" alt="Screen Shot 2021-03-15 at 5 53 59 PM" src="https://user-images.githubusercontent.com/9755669/111239935-772ed780-85b7-11eb-8355-55b7ce602962.png">

**Comment by KitsuneSolar** [comment]
Перевод обновлён до beta.16
Обновите движок, затем попробуйте обновить перевод.

**Comment by KitsuneSolar** [comment]
Понизил версию обратно до beta.15

Пробуйте:

```
composer update marketplace/flarum-l10n-ext-russian
php flarum cache:clear
```

**Comment by akairat** [comment]
Только что попробовал, все равно не работает. Пусть пока issue открытой постоит, если у кого еще подобная проблема. Если никто больше не ответит, скорее всего проблема в моей установке.

**Comment by KitsuneSolar** [comment]
У меня работает. Сорри за фото, сервер развёрнут на другом ПК.

![IMG20210316073652](https://user-images.githubusercontent.com/12877339/111256649-a03c8000-862a-11eb-8108-2b043392f7f3.jpg)

**Comment by akairat** [comment]
Понятно, значит проблема в моей установке, будем решать. Спасибо что проверили!
